<?php
return[
    "pdo"=>[
        "driver"=>"mysql",
        "host"=>"127.0.0.1",
        "dbname"=>"bug_tracker",
        "user"=>"root",
        "password"=>"root"
    ],
    "pdo_testing"=>[
        "driver"=>"mysql",
        "host"=>"127.0.0.1",
        "dbname"=>"bug_tracker_testing",
        "user"=>"root",
        "password"=>"root"
    ],
];